### ISSUE TITLE
differing output compared with 2005 UW version in C

### ISSUE THREAD

**Issue by idallen** [rjwhite/lc#1]
UW version (`static char *RCSid = "$Header: /fsys2/source/mfcf-misc/lc/RCS/lc.c,v 1.25 2005/10/27 16:59:58 rbutterworth Exp $";`) running `lc /dev` in an 80-column `urxvt` terminal inside `tmux` (excerpt of the full output):
~~~
Char. Spec. Files:
adsp           autofs         btrfs-control  console        cpu_dma_latency
cuse           dsp            ecryptfs       fb0            fb1
full           fuse           hidraw0        hidraw1        hpet
hwrng          i2c-0          i2c-1          i2c-10         i2c-2
i2c-3          i2c-4          i2c-5          i2c-6          i2c-7
i2c-8          i2c-9          kmsg           kvm            libmtp-3-13.1
~~~
Your version (`my $version = 'v0.3' ;`):
~~~
Char. Spec. Files:
adsp           autofs         btrfs-control  console        
cpu_dma_latency               cuse           dsp            ecryptfs
fb0            fb1            full           fuse           hidraw0
hidraw1        hpet           hwrng          i2c-0          i2c-1
i2c-10         i2c-2          i2c-3          i2c-4          i2c-5
i2c-6          i2c-7          i2c-8          i2c-9          kmsg
~~~
Also, the UW version puts Pipes after Files at the top of the listing.

**Comment by rjwhite** [comment]
I have uploaded a new 0.4 version that addresses this issue as well as some others I noticed.

This issue has 3 parts:
### 1.1 differing output display
That the output data is slightly different, specifically the file  'cpu_dma_latency' is on the next line in my version as opposed to the end of the line in the original C version.

### 1.2 missing items?
My program is missing the items (the last line) of:

        kvm            libmtp-3-13.1

### 1.3 ordering of file-types
the UW version puts Pipes after Sockets at the bottom of the listing

## 1.1 differing output display
My new version, although a complete rewrite of how the output is displayed, is the same for this specific case .  I rewrote it because it was over-complicated and difficult to understand.  However, my version is logically consistent in how it treats each column.
While it would be reasonable to assume that the UW version, which has a default display width of 80 characters and 5 columns would be 15 characters of data and 1 space - to have a total column width of (15+1)= 16 * 5 columns of 80 bytes, in actual fact it is 14 characters - leaving 5 characters of free space at the end.

If '**cpu_dma_latency**' were in any other columns, it would occupy 2 columns (30 chars) because it is 15 characters, otherwise there is no room for separation between fields.  The C version, because it has some extra room at the end (5 characters) in the default case (80 chars) allows it to be displayed at the end.  While I believe the UW version is aesthetically more pleasing, I'm currently not keen on an awful hack to implement a special case for the last column.  I may change my mind in the future.  I did mimic the 14 character true width and 5 columns, but I don't want to jump through hoops to be completely identical when I personally don't think it's a big deal to not be a perfect clone.
 The code had already stated in comments at the top that I was:

        "fixing some bugs, and slightly changed some behavior.

I have now updated the README.md to make it clear I am not claiming a perfect clone.

Meanwhile, I'm going to leave this issue open for now in case I change my mind or find the time to elegantly modify it to make it more aesthetically pleasing like the original C version.  My current method of handling column widths and display is painful to make a special case.  I may make it smarter in the future.

## 1.2 missing items
I replicated a directory of files that you describe and I cannot replicate the missing line of the two last files - nor do I see anyway in the (old) code that they would be left out.

### 1.3 ordering of file-types
You reference the 2005 version of lc that "**the UW version puts Pipes after Sockets at the bottom of the listing**."
 I ran the 1987 version that I have, as well as the 2006 version from John Sellens version of GitHub, and checked the code for each, and found that the "**Pipes**" come after the "**Files**", not the **Sockets**.

However, I did find that my version was not printing the file-types in the same order as the C version, so I have updated that so it is consistent with the 1978 and 2006 versions of lc that I see.

**Comment by rjwhite** [comment]
OK, it was driving me nuts that my version was not as aesthetically pleasing as the UW C version in the handling of the last column.  I've uploaded version 0.5 now and the output from it will now match your example.
There are still ocassions where they will be different, however, I believe my version is better than the original in that if there is room to squeeze a slightly over-sized item onto the last column at the end of the line, it will do a slightly better effort, so long as there is enough room with the terminal width.

An example of the difference between the original UW version and mine, with a terminal width of 80 characters is:

The UW version:

    server5> lc -f ~ | head -4
    Files:
    .ICEauthority  .TransferManager.db           .Xauthority    .Xmodmap.hide
    .Xresources    .abcde.conf    .aliases       .anyconnect
    .aspell.en.prepl              .aspell.en.pws .bash_history  .bash_logout
    ...

and my version:

```
server5> lc -f ~ | head -4
Files:
.ICEauthority  .TransferManager.db           .Xauthority    .Xmodmap.hide
.Xresources    .abcde.conf    .aliases       .anyconnect    .aspell.en.prepl
.aspell.en.pws .bash_history  .bash_logout   .cshrc         .did
...
```
You can see on the 2nd line of Files that **.aspell.en.prepl** has been squeezed in, on this 80 character terminal.

**Comment by idallen** [comment]
1.1 Thanks for the better-looking output.
1.2 There were no files missing; those outputs were only excerpts.
1.3 I mis-spoke.  I've edited my comment to say: *Also, the UW version puts Pipes after Files at the top of the listing.*

The output is now identical:
~~~
$ diff <(./lc.plx /dev) <(lc /dev)
$
~~~
